### ISSUE TITLE
RepresentationMap should be able to reference Valuelist

### ISSUE THREAD

**Issue by agent96** [glennmdt/sdmx-ml#102]
The RepresentationMapType is linked to common:CodelistReferenceType, I think this should be AnyCodelistReferenceType allowing it to map from a source/target ValueList and/or Codelist

**Comment by glennmdt** [comment]
Email trail for reference only
[XML Schemas - ticket 102.pdf](https://github.com/glennmdt/sdmx-ml/files/7152531/XML.Schemas.-.ticket.102.pdf)
[J Gager - ticket 102 completion confirmation.pdf](https://github.com/glennmdt/sdmx-ml/files/7152539/J.Gager.-.ticket.102.completion.confirmation.pdf)

**Comment by glennmdt** [comment]
Closed - included in sdmx3mdt repo commit 14
