### ISSUE TITLE
Jens Dossé - superfluous reference metadata structure

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#12]
By email from Jens 21/03/2021 @dosse

Hello J,

While looking through the new 3.0.0 schemas, I saw the follow:
The agreed referential metadata document from Matt promised a significantly reduced MSD complexity:

![refmetadata](https://user-images.githubusercontent.com/26928385/111984220-fade4c00-8b02-11eb-89c7-8ca57c997e64.jpg)

When looking at the new sdmx3.0.0 schemas, I still see additional structural that seem superfluous to me. This is a generated xml sample from the current XSD proposal:

               <structure:MetadataStructures>
                              <structure:MetadataStructure agencyID="agencyID49" isExternalReference="false" serviceURL="http://www.oxygenxml.com/" structureURL="http://www.oxygenxml.com/"
                                             id="id380" version="1.0" validFrom="2006-05-04T18:13:51.0" validTo="2006-05-04T18:13:51.0" urn="http://www.oxygenxml.com/"
                                             uri="http://www.oxygenxml.com/">
                                             <structure:MetadataStructureComponents>
                                                            <structure:ReportStructure id="id386" urn="http://www.oxygenxml.com/" uri="http://www.oxygenxml.com/">
                                                                           <structure:MetadataAttribute minOccurs="1" maxOccurs="1" isPresentational="false" id="id392" urn="http://www.oxygenxml.com/" uri="http://www.oxygenxml.com/">
                                                                                          <structure:ConceptIdentity>
                                                                                                         <URN xmlns="">http://www.oxygenxml.com/</URN>
                                                                                          </structure:ConceptIdentity>
                                                                           </structure:MetadataAttribute>
                                                                           <structure:MetadataAttribute minOccurs="1" maxOccurs="1" isPresentational="false" id="id394" urn="http://www.oxygenxml.com/" uri="http://www.oxygenxml.com/">
                                                                                          <structure:ConceptIdentity>
                                                                                                         <URN xmlns="">http://www.oxygenxml.com/</URN>
                                                                                          </structure:ConceptIdentity>
                                                                           </structure:MetadataAttribute>
                                                            </structure:ReportStructure>
                                             </structure:MetadataStructureComponents>
                              </structure:MetadataStructure>
               </structure:MetadataStructures>

- MetadataStructureComponents: “describes the structure of the grouping of the sets of the components that make up the metadata structure definition. At a minimum, a full target identifier and at least one report structure must be defined.” 
Without the target identifier this object has no usage, I believe.
- ReportStructure “defines a report structure, which comprises a set of metadata attributes that can be defined as a hierarchy, for reporting reference metadata about a target object.” 
We also should not need this level anymore.
Thus the MetadataAttribute could indeed be directly attached to the MetadataStructure. I have further simplified the schema files on my laptop and regenerated a new xml sample:

               <structure:MetadataStructures>
                              <structure:MetadataStructure agencyID="F-" isExternalReference="false" serviceURL="http://sZcuklrK/" structureURL="http://aMeusFAP/" id="-" version="1.0" validFrom="2022-02-26T23:32:15" validTo="2022-06-20T23:32:15Z" urn="http://NUXxpwdy/" uri="http://bsnAGQSt/">
                                             <common:Name xml:lang="en">zUDK3TpEcS</common:Name>
                                             <common:Name xml:lang="en">Q</common:Name>
                                             <structure:MetadataAttribute minOccurs="1" maxOccurs="1" isPresentational="false" id="E" urn="http://JyLCEtyX/" uri="http://iVlHyXHK/">
                                                            <structure:ConceptIdentity>
                                                                           <URN>http://NEuJYxrR/</URN>
                                                            </structure:ConceptIdentity>
                                                            <structure:LocalRepresentation minOccurs="1" maxOccurs="1">
                                                                           <structure:TextFormat textType="String" isSequence="1" interval="1065479131.152" startValue="2127679181.418" endValue="788748633.806"
                                                                                          timeInterval="P6Y9M2DT1H10M0S" startTime="startTime" endTime="endTime" minLength="1243219246"
                                                                                          maxLength="1632582998" minValue="-1741185300.494" maxValue="866254460.465" decimals="799283398"
                                                                                          pattern="MkWB" isMultiLingual="true"/>
                                                            </structure:LocalRepresentation>
                                                            <structure:MetadataAttribute minOccurs="1" maxOccurs="1" isPresentational="false" id="D" urn="http://EoDHeegt/" uri="http://EjaIEqiL/">
                                                                           <structure:ConceptIdentity>
                                                                                          <URN>http://qLZrnyLV/</URN>
                                                                           </structure:ConceptIdentity>
                                                                           <structure:LocalRepresentation minOccurs="1" maxOccurs="1">
                                                                                          <structure:Enumeration>
                                                                                                         <Ref class="ValueList" package="codelist" agencyID="jx-" id="$" version="1.0" local="false"/>
                                                                                          </structure:Enumeration>
                                                                           </structure:LocalRepresentation>
                                                            </structure:MetadataAttribute>
                                             </structure:MetadataAttribute>
                                             <structure:MetadataAttribute minOccurs="1" maxOccurs="1" isPresentational="false" id="Z" urn="http://PooaWSXJ/" uri="http://LZKIsRaX/">
                                                            …
                                             </structure:MetadataAttribute>
                              </structure:MetadataStructure>

I have attached the files that would need to be changed.
(SDMXStructure.xsd, SDMXStructureMetadataStructure.xsd, SDMXMetadataGeneric.xsd)

Could you please have a look at this?

**Comment by jgager** [comment]
The reason the MetadataStructureComponents and ReportStructure were left in place is because the MetadataStructureDefinition still needs to conform to the generic Structure abstract type (which has a grouping (MetadataStrcutureComponents) of 1..n component lists (ReportStructure)). Based on the version of the model I was working off from, this was not changed. If I make the changes as you suggest, the derivation is invalid:

```
[Error] SDMXStructureMetadataStructure_jens.xsd:12:47: rcase-Recurse.2: There is not a complete functional mapping between the particles.
[Error] SDMXStructureMetadataStructure_jens.xsd:12:47: derivation-ok-restriction.5.4.2: Error for type 'MetadataStructureType'.  The particle of the type is not a valid restriction of the particle of the base.
```

The structure that you suggest effectively makes the MeadataStructure a component list (with the attributes being the components). However, ComponentList is only Identifiable, so we lose the maintenance. We would effectively need to new base type for this to do what you propose. I am fine to change this, but we need the model to reflect this first.

**Comment by dosse** [comment]
@jgager I see. In order to align with the DSD approach you could maybe have an intermediate "AttributeList" level (based on the ComponentList type)? It's ok for MSD as long as it is not more complicated than the DSD. Thanks a lot.

**Comment by jgager** [comment]
Update pushed to fork.

@dosse I should have caught this earlier, but the name has to be MetadataAttributeList as there is already an global AttributeList element (from the DSD) in the structure namespace.

**Comment by dosse** [comment]
> Update pushed to fork.
> 
> @dosse I should have caught this earlier, but the name has to be MetadataAttributeList as there is already an global AttributeList element (from the DSD) in the structure namespace.

Ok, it sound good to me.

**Comment by stratosn** [comment]
@dosse , @jgager do you confirm that the IM should be updated accordingly, i.e., create a MetadataAttributeDescriptor?

**Comment by glennmdt** [comment]
@stratosn has the model been updated with MetadataAttributeDescriptor as you recommended? 
I just thought it good to confirm there's nothing outstanding before closing the ticket.

**Comment by stratosn** [comment]
@glennmdt yes, it has been updated accordingly.

**Comment by glennmdt** [comment]
@stratosn perfect. Issue closed ;-)
