### ISSUE TITLE
Jens Dossé - MetadataSets should not link to a MetadataStructure, and 'Att' vs 'Attribute'

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#13]
By email from Jens 21/03/2021 @dosse

I also saw that you have already implemented the referential metadata message (MetadataSets). It looks generally good. 

There is just one issue: According to Matt’s document that was agreed, MetadataSets can only be linked to a Metadataflow or a MetadataProvisionAgreement, but not to a MetadataStructure, because the MetadataStructure doesn’t define any allowed targets. I have attached to corrected schema file. 
I also think that “Att” is a bit too short for “Attribute”, almost not understandable (could be “attention”, “attenuation”, “attestation”, “attainment”, “attitude”, “attachment”, …), I have extended it to “Attr” at least, but wonder why it needs to be abbreviated. Usually, there shouldn’t be too many of these attributes (while their content can be huge), thus writing the full word “Attribute” should not represent an issue. 
Now, a generated XML sample looks like this:

               <message:MetadataSet structureRef="ID001" action="Information" reportingBeginDate="2022-01-25T23:32:15Z" reportingEndDate="2002" publicationYear="1998Z" publicationPeriod="publicationPeriod" agencyID="v.X-_j" isExternalReference="false" serviceURL="http://OimTcbcs/" structureURL="http://KMDKyWvR/" id="P" version="1.0" validFrom="2022-12-02T23:32:15Z" validTo="2022-05-12T23:32:15" urn="http://ccBzsSvi/" uri="http://kcehAVRW/">
                              <common:Name xml:lang="en">tQ1t_9</common:Name>
                              <common:Name xml:lang="en">imsh9YiatuJtHM_FO.Z</common:Name>
                              <metadata:MetadataProvisionAgreement>
                                             <URN>http://kmetdudZ/</URN>
                              </metadata:MetadataProvisionAgreement>

                              <metadata:Target>
                                             <URN>http://uyxHDMxv/</URN>
                              </metadata:Target>
                              <metadata:Target>
                                             <Ref agencyID="e.B" local="false" class="MetadataTarget" package="base" maintainableParentID="R" maintainableParentVersion="1.0.0"
                                                            containerID="*" id="--$" version="0.0.8"/>
                                             <URN>http://UunWtqNs/</URN>
                              </metadata:Target>
                              <metadata:Attr id="_0">
                                             <metadata:Value>VbN66JCU9xF_5wNGVv</metadata:Value>
                                             <metadata:Value>mZw22DcG_i7zB5e_zfNA7z9hq1</metadata:Value>
                                             <metadata:Attr id="Y_r">
                                                            <common:Text xml:lang="en">vj0Sl589Vo2QMweF.K</common:Text>
                                                            <common:Text xml:lang="en">Sr8QqZd1Bcw0yY4</common:Text>
                                             </metadata:Attr>
                                             <metadata:Attr id="Ag">
                                                            <metadata:Value>pSWG8mh_SLVt</metadata:Value>
                                                            <metadata:Value>F9Tor7qxzk_1NZH0-oMNX9Vo3c63Mf</metadata:Value>
                                             </metadata:Attr>
                              </metadata:Attr>
                              <metadata:Attr id="$Nc">
                                             <common:Text xml:lang="en">nJ237s5WifKTDnQ7n9BTE</common:Text>
                                             <common:Text xml:lang="en">E0IMCF7Dn.UAJPGD</common:Text>
                                             <metadata:Attr id="t">
                                                            <common:StructuredText xml:lang="en">
                                                            </common:StructuredText>
                                                            <common:StructuredText xml:lang="en">
                                                            </common:StructuredText>
                                             </metadata:Attr>
                              </metadata:Attr>
               </message:MetadataSet>
Thanks a lot,
Jens

**Comment by jgager** [comment]
Removed option to reference MetadataStructure and updated Att to Attribute

**Comment by glennmdt** [comment]
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601636627

**Comment by glennmdt** [comment]
@dosse changes have been made - please can you verify? Everything is on the https://github.com/sdmx-twg/sdmx-ml/pull/21 pull request.

**Comment by dosse** [comment]
Ok, great, thanks.

**Comment by glennmdt** [comment]
@dosse perfect, thanks for the review. Ticket closed.
