### ISSUE TITLE
Metadata reuse in DSD: Missing link to MSD

### ISSUE THREAD

**Issue by dosse** [glennmdt/sdmx-ml#14]
@jgager @glennmdt Please let me know if I'm looking at the wrong place, but I cannot find where the DSD links to an MSD to include its attributes and allow adding related relationships as agreed in the Quality Review phase. Instead I still see the discarded "Metadata" as UsageStatus (https://github.com/glennmdt/sdmx-ml/blob/adfbfaae4e532bc9ecf057de19a6645c6fba8532/v3_0/schemas/SDMXStructureDataStructure.xsd#L614). This type of UsageStatus is not required because the attribute type is clear through the link to the MSD and also because data messages allow exchanging separately ANY type of attribute.

**Comment by glennmdt** [comment]
@dosse If this is the recently approved design change detailed in CCR-01 [http://localhost/metatech11/sdmx3/designs/001/revisions/SDMX%203.0%20Feature%20001%20Change%20Control%20Request%2024Feb21.docx](url) then it hasn't been implemented yet.
The current schemas reflect the 'baseline' Information Model - that used for the Quality Review. After Stratos has completed a stable baseline version of the core technical specs by fixing all of the identified bugs, the plan is to make incremental revisions to apply the outstanding changes including the agreed CCR-01 modifications to the reference metadata model. This process is to ensure we don't miss anything and avoid the schemas are kept in sync with the model.
See [https://metadatatechnology.com/sdmx3/](url) Specifications tab.

**Comment by jgager** [comment]
Leaving until after baseline schema review is complete.

**Comment by glennmdt** [comment]
This is now ready to implemented.
For reference, there's a link to the final draft Section 2 on the project website 
[https://metadatatechnology.com/sdmx3/](url)

**Comment by jgager** [comment]
@glennmdt change is pushed into fork

**Comment by glennmdt** [comment]
@dosse changes have been made - please can you verify? Everything is on the https://github.com/sdmx-twg/sdmx-ml/pull/21 pull request.

**Comment by dosse** [comment]
ok, great, thanks.
