### ISSUE TITLE
Metadata Structure Definition model change - remove ReportStructure

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#15]
MSD Model Change
Remove ReportStructure which is now redundant from MetadataStructureComponentsType.

Refer to sdmx-twg pull request comment [https://github.com/sdmx-twg/sdmx-ml/pull/21#issuecomment-807529473](url)

Revised MSD model is shown in Tech Specs Section 2 DRAFT 0.9 paragraph 7.3 [https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EW5KwIO6JYFHkb9eLR4RGKUBqMSWsuWrR37WcaFDi663dQ?e=ZQosK8](url)
Change from DRAFT 0.7 to DRAFT 0.9

**Comment by jgager** [comment]
See [issue 12](https://github.com/glennmdt/sdmx-ml/issues/12). ReportStructure is now renamed to MetadataAttributeList. This is necessary for derivation purposes and to ensure the element name is unique.
