### ISSUE TITLE
Add 'FixedValueMap' to StructureMap structure

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#17]
Model Change - StructureMap

Add FixedValueMap to the StructureMap structure.
A bug was spotted in the model whereby there was no way to map fixed values.

See Section 2 DRAFT 0.9 paragraph 9.1.1 [https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EW5KwIO6JYFHkb9eLR4RGKUBqMSWsuWrR37WcaFDi663dQ?e=ZQosK8](url)

Source: Stratos

**Comment by jgager** [comment]
Update committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
