### ISSUE TITLE
SDMXRegistryBase.xsd - DataSourceType looks incorrect

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#18]
Reference Section 2 DRAFT 0.9 Figure 40 Page 134  [https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EW5KwIO6JYFHkb9eLR4RGKUBqMSWsuWrR37WcaFDi663dQ?e=ZQosK8](url)
The model shows QueryDatasource and SimpleDatasource which differ from  the DataSourceType:

![DataSourceType](https://user-images.githubusercontent.com/26928385/112300001-48d48a80-8c90-11eb-925e-5328d0b2e63d.png)

The QueryDatasource annotation also shouldn't refer to SDMX-ML query messages which have been deprecated in favour of REST GET calls.

**Comment by jgager** [comment]
Update committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
