### ISSUE TITLE
Add locale to DatePatternMap

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#20]
Model Change - locale property added to DatePatternMap

Reference Section 2 DRAFT 0.9 page 113 [https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EW5KwIO6JYFHkb9eLR4RGKUBqMSWsuWrR37WcaFDi663dQ?e=ZQosK8](url)

Source: Stratos

**Comment by jgager** [comment]
Update committed to fork.

@glennmdt  Note that the schema and the model are not completely aligned; the model shows a DatePatternMap composing a collection of DateMappings. The locale and sourcePattern attributes exist on the DateMappings. It is not clear why the DatePatternMap would define more than one pattern. Based on the previous conversions we had, I think the schema is correct. However, we should discuss and review the model and schemas to get them aligned.

**Comment by sdmx3mdt** [comment]
@jgager  Matt has reviewed the schema and thinks it's okay. It's not precisely as described in the model, but can achieve the same result, and is a bit simpler.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
