### ISSUE TITLE
Remove ConceptScheme from VtlMappingType - VTL model change

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#23]
Model Change - the VTLConceptSchemeMapping class has been removed 

Remove ConceptScheme from VtlMappingType - it's not needed in version 3.0.

Reference Section 2 DRAFT 0.9 Page 144 [https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EW5KwIO6JYFHkb9eLR4RGKUBqMSWsuWrR37WcaFDi663dQ?e=ZQosK8](url)

Reason for change:
Modification by Vincenzo to the VTL / SDMX interface specification to align with the SDMX 3.0 model.

**Comment by jgager** [comment]
Update committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
