### ISSUE TITLE
Item Maps all support multiple source/targets even if container does not

### ISSUE THREAD

**Issue by agent96** [glennmdt/sdmx-ml#24]
The codelist map supports multiple source/target codelists and the item maps mirror this by supporting multiple source items - this is as designed.  Other maps such as the concept scheme map only contain one source and one target concept scheme, but the item maps support multiple source/targets.  I'm not sure other itemscheme maps need to support multiple source/targets.

**Comment by jgager** [comment]
@agent96 what schema is this in reference to? Is this structure mapping or VTL?

**Comment by agent96** [comment]
Structure Mapping

**Comment by jgager** [comment]
@agent96 Is the change request here to make the ItemScheme/ItemMap/[SourceValue | TargetValue] non-repeatable (i.e. 0..1)?

**Comment by agent96** [comment]
Yes, with the exception of a Representation Map which can have multiple (to support the Structure Map with multiple source/target Components)

**Comment by glennmdt** [comment]
@jgager has the change been made?

**Comment by jgager** [comment]
@glennmdt I just pushed this into the working fork

**Comment by glennmdt** [comment]
Perfect - closing ticket.
