### ISSUE TITLE
Metadata Set structureRef

### ISSUE THREAD

**Issue by agent96** [glennmdt/sdmx-ml#25]
The reference from a metadata set to a structre is in the Metadata Set itself, but there is still the structureRef attribute on the metadata set whcih points back to the header.  I don't think the Header needs a Structure element in this context and the stuctureRef attribute is not required.

**Comment by jgager** [comment]
Update committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
