### ISSUE TITLE
Structure 'version' attribute annotation out of date

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#26]
The structure 'version' attribute still states that, if not supplied, the version number defaults to 1.0. It should say that if not supplied, the structure is considered to be un-versioned.
The behaviour was changed in 3.0 with the introduction of semantic versioning.
Section 6 para 4.4 explains the detail.

![VersionDefault](https://user-images.githubusercontent.com/26928385/112361435-48a5b080-8ccb-11eb-8a58-762b9484a57d.PNG)

https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601673332

**Comment by jgager** [comment]
Update is committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
