### ISSUE TITLE
SDMXCommon.xsd default should be non-versioned rather than 1.0

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#27]
sdmx-twg pull request comment
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601672594 

If the version is not specified then the artefact is now non-versioned, rather than having version "1.0". The default should be removed. 
This is a change in SDMX 3.0 associated with the introduction of semantic versioning.

**Comment by jgager** [comment]
See https://github.com/glennmdt/sdmx-ml/issues/26. Update committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
