### ISSUE TITLE
SDMXCommonReferences.xsd SemanticVersionNumberType regex could be simplified

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#28]
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601685993

Possible shorter regex suggested in the semver design document:
^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?$

<xs:simpleType name="SemanticVersionNumberType">
		<xs:annotation>
			<xs:documentation>SemanticVersionNumberType is a simple type for validating semantic version in the format (major.minor.patch[-extension]).</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(0|[1-9]\d*)(\.(0|[1-9]\d*)){2}(\-(([A-Za-z\-]|([A-Za-z\-][A-Za-z0-9\-]+)|([A-Za-z0-9\-]+[A-Za-z\-][A-Za-z0-9\-]*))|(0|[1-9][0-9]*))(\.(([A-Za-z\-]|([A-Za-z\-][A-Za-z0-9\-]+)|([A-Za-z0-9\-]+[A-Za-z\-][A-Za-z0-9\-]*))|(0|[1-9][0-9]*)))*)?"/>
		</xs:restriction>
	</xs:simpleType>

**Comment by jgager** [comment]
@glennmdt XML Schema only implements a subset of regex, and this subset does not include look aheads. The expanded pattern I created works around these limitations and, to the best of my knowledge, performs the same validation.

**Comment by glennmdt** [comment]
Acknowledged

**Comment by jgager** [comment]
@dosse Based on [this page](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html), JSON schema does support positive and negative lookaheads, so the shortened version suggested in the design document should work. However, the pattern I wrote for XSD should accomplish the same thing, it is just more verbose (and probably a tad more complicated to read).
