### ISSUE TITLE
SDMXStructureOrganisation.xsd - organisation schemes will not use a version number any more

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#29]
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601708985 

The semantic versioning feature document states: "The OrganisationScheme artefacts will not use a version number anymore." The version should be removed from this type.

**Comment by jgager** [comment]
Update is committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
