### ISSUE TITLE
'GeospatialInformation' missing from common:DataType enumeration 

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#3]
A new 'GeospatialInformation' DataType is required, but it's missing from the list.

The following should be valid:
<str:LocalRepresentation>
	<str:TextFormat isSequence="false" textType="GeospatialInformation"/>
</str:LocalRepresentation>

See Section 6.1.2 in:
[https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EdzQ20XiZFdKhn-7LaF-EIwBldtM8QoAGoVw7kDmqLXerg?e=2U6Lj7](url)

The value of a GeospatialInformation component in transmitted data is a string describing an arbitrarily complex set of geographic features using a syntax that would best be defined using EBNF, but it may be possible in RegEx. 

Conceptual example:
"CRS, PRECISION: {GEO_FEATURE_TYPE: X_CORDINATE, Y_COORDINATE, ALT; X_CORDINATE, Y_COORDINATE, ALT; X_CORDINATE, Y_COORDINATE, ALT;…:GEO_DESCRIPTION}, {GEO_FEATURE_TYPE: X_CORDINATE, Y_COORDINATE, ALT; X_CORDINATE, Y_COORDINATE, ALT; X_CORDINATE, Y_COORDINATE, ALT;…:GEO_DESCRIPTION }, …: GEO_DESCRIPTION"

The specification calls for the XML (and JSON) schemas for the data and metadata messages to validate that GeospatialInformation values are syntactically correct according to that grammar.

**Is it possible to create a pattern restriction to do this sort of validation of string values with relative complex grammars?**
**If not, just treat as a string**

**Comment by jgager** [comment]
The addition of GeospatialInformation to the DataType enumeration and the derived BasicComponentDataType and SimpleDataType enumerations is pushed into develop. Note that it was not included in the CodeDataType restriction, which is used when the component is using an enumeration (e.g. a geo code list). The rationale here is that the value carried is not the geo information, but rather the code pointing to it. If that is not the intention, please clarify.

As for the simple type to validate this, I do not think that the EBNF is fleshed out enough to attempt that. The allowable characters for the components (CRS, PRECISION, X_COORDINATE, GEO_DESCRIPTION) are not defined in the linked document. If these are described, we can take a shot at the regex. For now though, I have only updated Part 3A section IV to map this text format type to xs:string.

**Comment by glennmdt** [comment]
CodeDataType
Yes, I believe that's correct. From a data perspective, a geo code looks the same as any other. It's just that a geo code list allows a richer definition of its codes.

EBNF
I agree. The grammar is ill defined. Leave as xs:string for now.
