### ISSUE TITLE
SDMXStructureOrganisation.xsd - documentation changes

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#30]
Documentation update...
In documentation replace "is always provided a fixed identifier and version, and is never final" with "is always provided a fixed identifier and is never versioned". Restrict the usage of the "version" attribute.

The documentation needs to be changed in five places as explained on each of these comments on the sdmx-twg/sdmx-ml pull request:
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601708985
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601711924
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601712368
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601712582
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r601712769

**Comment by jgager** [comment]
Update is committed to fork.

**Comment by glennmdt** [comment]
Pushed to sdmx3mdt branch commit 7
