### ISSUE TITLE
Now that we have the occurrences for both Attributes and Measures, is there a reason keeping assignmentStatus?

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#31]
Question from @stratosn on the XML schemas:

Now that we have the occurrences for both Attributes and Measures, is there a reason keeping assignmentStatus?

**Comment by jgager** [comment]
I suppose we do not. I will remove it.

**Comment by glennmdt** [comment]
@jgager has this change been made?

**Comment by jgager** [comment]
@glennmdt I have pushed to the working fork now

**Comment by glennmdt** [comment]
Perfect - thanks. Closing ticket.
