### ISSUE TITLE
Structure Specific Data - DataSet structureRef attribute duplicated

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#32]
DataSetType looks like it has duplicate structureRef attributes.

![structureRef](https://user-images.githubusercontent.com/26928385/114200662-5440da80-994d-11eb-86ed-09e4d9b5c7ec.PNG)

The following is valid in a data message:
<message:DataSet ss:dataScope="DataStructure" xsi:type="ns1:DataSetType" ss:structureRef="ECB_EXR_1_0" structureRef="ECB_EXR_1_0">

**Comment by jgager** [comment]
@glennmdt change is pushed into fork

**Comment by glennmdt** [comment]
Fixed. Closing ticket.
