### ISSUE TITLE
Add support for Sentinel Values in Attributes and Measures

### ISSUE THREAD

**Issue by stratosn** [glennmdt/sdmx-ml#33]
The support for Sentinel Values is foreseen as a new `facetType` that will result into a set of special values within the `textType` data type of the Component. Those special values, may also have multilingual names and descriptions.
For example:
```xml
<str:LocalRepresentation>
  <str:TextFormat textType="Integer" sentinelValues="true">
    <str:Sentinel value="-1">
      <com:Name xml:lang="en">Non-response</com:Name>
    </str:Sentinel>
    <str:Sentinel value="-2">
      <com:Name xml:lang="en">Not applicable</com:Name>
    </str:Sentinel>
  </str:TextFormat>
</str:LocalRepresentation>
```

**Comment by jgager** [comment]
@stratosn I have implemented this, but have taken in out of specific refinements where it should not be used (e.g. coded representations). One place I did leave it in is time representations as I have seen cases where specific dates are used to indicate that the date is actually missing. If you feel this need to be removed from here as well, please let me know.

**Comment by jgager** [comment]
@glennmdt change is pushed into fork

**Comment by stratosn** [comment]
@jgager I'm fine with the proposed implementation.

**Comment by glennmdt** [comment]
Change made. Closing ticket.
