### ISSUE TITLE
Add more contraining terms in DataKeysets and CubeRegion

### ISSUE THREAD

**Issue by stratosn** [glennmdt/sdmx-ml#34]
As a result of the new reference metadata design, but also the reorganisation of Constraints, there is a need to add constraining terms for Measures and MetadataAttributes, in `CubeRegion` and `Key`.

In addition, following the microdata support, for all Components that have multilingual representations, an optional locale (or lang) property needs to be added in their `Value`.

Finally, due the codelist extensions, the ability to remove prefixes (that may have been added at the extension time), must be supported by using the `removePrefix` property within `KeyValue`.

**Comment by jgager** [comment]
@stratosn I have implemented this as follows:

- for CubeRegion and Key, I update the Attributes to Components and changed the documentation to reflect that this could be used for data attributes, metadata attributes, or measures
- for the multi-lingual, I have added xml:lang to the values (removed from the data keys) as it would not apply there
- the removePrefix should already be inherited from the base structure; let me know if I am not understanding the request correctly

**Comment by jgager** [comment]
@glennmdt change is pushed into fork

**Comment by glennmdt** [comment]
Fixed. Closing ticket.
