### ISSUE TITLE
AttributeRelationship missing from MetadataAttribute?

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#36]
Section 2 (DRAFT 1.0) quotes:
"A DataAttribute or a MetadataAttribute (i.e., an AttributeComponent) is specified as being +relatedTo an AttributeRelationship, which defines the constructs to which the AttributeComponent is to be reported present in a DataSet."
![AttributeRelationship](https://user-images.githubusercontent.com/26928385/114624225-491ce000-9ca8-11eb-8507-44316f19b35f.png)

However, I can't see that reflected in the MetadataAttribute schema:
![MetdataAttribute](https://user-images.githubusercontent.com/26928385/114624668-f2fc6c80-9ca8-11eb-834e-5935ab08c8ff.PNG)

Am I looking in the wrong place?

**Comment by glennmdt** [comment]
@stratosn am I write in saying that, in the latest model, a MetadataAttribute should have an AttributeRelationship just like that for data?

**Comment by stratosn** [comment]
I would say something like this: 
`A MetadataAttribute may have an AttributeRelationship like a DataAttribute.`

**Comment by sdmx3mdt** [comment]
Sorry @stratosn, what I meant was that in the current XML schema, the DataAttribute has an AttributeRelationship element, but MetadataAttribute does not. Should it?

**Comment by stratosn** [comment]
Yes, MetadataAttributes need to be related to observations, series, or all in order to be positioned properly.

**Comment by jgager** [comment]
@stratosn @glennmdt I do not think we can simply add AttributeRelationship to the exists MetadataAttributeType because it is meant to contain local references to data structure components, which do not exist in the metadata structure in which the metadata attribute is defined.

Instead, I have implemented this as follows:

- define a component in the data structure module named MetadataAttributeUsage
    - the structure of the this is a local reference to the metadata attribute (since the metadata structure is already referenced from the data structure) and an optional attribute relationship
    - note the name could not be MetadataAttribute since that is already used in the namespace
    - this structure allows an existing metadata attribute to be further described in the context of a data structure
- add this component to the existing AttributeList

See this commit for details: https://github.com/glennmdt/sdmx-ml/commit/88db630699d3ec46365de8dd06f2973656d5f18b.

One part I am still not clear on is how this relates to the actual data message? Can metadata attributes now be included directly in the data message?

**Comment by jgager** [comment]
@glennmdt change is pushed into fork

**Comment by stratosn** [comment]
@jgager the idea is that within a DSD the user is able to add MetadataAttributes (as defined in the related MSD) in the AttributeDescriptor. Hence, they would be able to appear in the data message just like DataAttributes. That's why we also need the 'relationship'.

**Comment by jgager** [comment]
@stratosn 

1. In terms of defining the metadata attribute in a metadata structure, the idea of the attribute relationship cannot exist, correct?
2. Are these metadata attributes part of the actual data message?
3. If yes on 2, then do we need to add a separate construct for metadata attributes to support the scenario where they have a complex structure (e.g. nested metadata attributes)?

**Comment by stratosn** [comment]
@jgager 
1. Yes, it is not part of the MSD, only the DSD.
2. Yes, they may be reported like DataAttributes (at any level within the Dataset)
3. Nesting is not supported here. Any MetadataAttribute can be only used as a single Attribute. Hence, any children are ignored.

**Comment by glennmdt** [comment]
Closing issue.
