### ISSUE TITLE
MetadataConstraint links to DataConstraintAttachmentType

### ISSUE THREAD

**Issue by stratosn** [glennmdt/sdmx-ml#37]
In the `SDMXStructureConstraint.xsd` the `ConstraintAttachment` element of the `MetadataConstraintBaseType` is of type `DataConstraintAttachmentType` instead of `MetadataConstraintAttachmentType`.

**Comment by jgager** [comment]
@glennmdt change is pushed into fork

**Comment by glennmdt** [comment]
Fixed. Closing issue.
