### ISSUE TITLE
VtlMappingScheme and ValueList

### ISSUE THREAD

**Issue by stratosn** [glennmdt/sdmx-ml#38]
Should the `ValueList` participate in the `VtlMappingScheme`'s possible `VtlMappings`?
This is also a question towards the **VTL TF**.
If yes, then it should be also added to the IM.

Currently, a `VtlMappingScheme` may include `VtlMappings` of the following types:
- `VtlCodelistMapping`
- `VtlDataflowMapping`
- `VtlConceptMapping`

**Comment by glennmdt** [comment]
Issued moved to post drafting phase repo https://github.com/sdmx3mdt/twg-issues/issues/2
