### ISSUE TITLE
Metadata Provision Agreement and Metadata Provider Scheme missing from XML Schemas

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#4]
Two structures are missing from the schemas:
* Metadata Provision Agreement
* Metadata Provider Scheme

They are essentially the same as the data equivalents except a Metadata Provision Agreement can link to any other artefact.

See section 7.3 in the following
[https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EflcBha7_PxBuFkeXu_dqRMBISBAy9IsjqXHjYkNHq321Q?e=ZCiUyI](url)

**Comment by jgager** [comment]
This update has been committed.
