### ISSUE TITLE
SDMXStructure.xsd -  Jens Dossé comment on container naming

### ISSUE THREAD

**Issue by sdmx3mdt** [glennmdt/sdmx-ml#40]
This ticket responds to sdmx-twg/sdmx-ml pull request review comment:
https://github.com/sdmx-twg/sdmx-ml/pull/21#discussion_r615293445

Synopsis:
Why not simply "StructureMaps" or "Maps" instead of "StructureMappings"? It is confusing that the containers change names compared to their content.
It should be "CustomTypeSchemes" instead of "CustomTypes", etc.
This also concerns "Concepts" that should be better "ConceptSchemes".

**Comment by jgager** [comment]
Hold until broader decision is finalized

**Comment by sdmx3mdt** [comment]
Superseded by [https://github.com/sdmx3mdt/public-consultation/issues/7](url)
