### ISSUE TITLE
Shouldn't the "FrequencyId" in "FrequencyFormatMappingType" not be of type "IDType"?

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#43]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/37

**Comment by jgager** [comment]
As I understand this, it is intended to provide a date format based on frequency values. Since there is no restriction that says the values of a frequency dimension has to be of a given type, xs:string is appropriate.

**Comment by glennmdt** [comment]
Noted. Jens Dosse asked to confirm whether he agrees.

**Comment by glennmdt** [comment]
Jens asked another question on https://github.com/sdmx3mdt/public-consultation/issues/37

**Comment by sdmx3mdt** [comment]
@jgager Matt advises on https://github.com/sdmx3mdt/public-consultation/issues/37 that some form of restriction is appropriate so I guess the action is to update to IDType as originally suggested?

**Comment by glennmdt** [comment]
Matt's advice - I think you are right in that it could be a non ID Type in theory, but it probably makes sense to restrict it, as the chances of a user both not using a known SDMX Frequency ID and using an ID that does not conform to IDType would be very slim.

Action - unless there's a specific reason why it needs to stay as xs:string, then I suggest updating to use IDType (or appropriate).

**Comment by jgager** [comment]
There are other elements similar to this:

- DatePatternMapType/TargetFrequencyID
- EpochMapType/TargetFrequencyID

Should these be IDType as well?

**Comment by glennmdt** [comment]
@jgager Matt agrees - these should be IDType.

* DatePatternMapType/TargetFrequencyID
* EpochMapType/TargetFrequencyID
*
@agent96 - for reference

**Comment by glennmdt** [comment]
Pushed to feature branch Commit 13
https://github.com/sdmx3mdt/sdmx-ml/commit/3dcfb8fc3b398e994ccb9f1779d828a7dced01b7
