### ISSUE TITLE
In schemas/SDMXStructureStructureMappings.xsd remove "ResolvePeriodType" since not used

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#47]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/32

**Comment by jgager** [comment]
Is this actually unused or is it missing from being used in DateMapType? It is still included in the information model.

**Comment by glennmdt** [comment]
An update to the mapping model is required – Matt @agent96 has found some issues when attempting to implement, so park this one for the moment pending completion of the modelling work.
Matt will redesign the model working from what he's found works in the Fusion Registry implementation.

**Comment by glennmdt** [comment]
Matt has proposed the changes needed to the Structure Mapping model https://github.com/sdmx3mdt/public-consultation/issues/53
In consequence, it looks like resolvePeriod is still used for DateMap so ResolvePeriodType is required.
As such, I'll close this ticket, and open another for Matt's changes.

**Comment by glennmdt** [comment]
No bug. 
Howver, ticket https://github.com/glennmdt/sdmx-ml/issues/76 has some additional changes to the mapping model.

**Comment by glennmdt** [comment]
ResolvePeriod is missing from DateMapType and should be added.

Excerpt from Section 2 DRAFT 0.1
![image](https://user-images.githubusercontent.com/26928385/128869630-c0e5a1d4-bfd3-4ffd-9fc8-ce3290be08ed.png)

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request.
Ticket will be reopened if pull request rejected.
