### ISSUE TITLE
SDMXStructure.xsd - DataConstraint is incorrectly assigned MetadataConstraintType

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#5]
<xs:element name="DataConstraint" type="MetadataConstraintType"> appears to be incorrect.

The attached structure message fails validation because the str:CubeRegion element is not valid under str:DataConstraint.
Changing the above to type="DataConstraintType" appears to fix the problem.

[codelist -disciminated union.zip](https://github.com/glennmdt/sdmx-ml/files/6122513/codelist.-disciminated.union.zip)

**Comment by jgager** [comment]
Fix is pushed to develop
