### ISSUE TITLE
Clarify/remove variances in URN class name lists

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#54]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/24

There's discrepancies in the list of URN class names between "[SDMX STANDARDS: SECTION 5 SDMX REGISTRY SPECIFICATION](https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EX9q-3Weh3ZDkt8K9TCxpkUBkpaC9V1fwqbeZ82DHudK_A?rtime=zA9-INAU2Ug)" (pages 31-33) and the class names listed in the "ObjectTypeCodelistType" type (in schemas/SDMXCommonReferences.xsd) used for the classes in the "WildcardObjectRefType" type. 

Action: reach agreement on a common list of URN class names with Stratos and update the schemas. Stratos will update Section 5.

**Comment by sdmx3mdt** [comment]
Update:
Stratos / Task Force 2 (Information Model) will define the list of URN class names in Section 5 which will then need to be reflected into the schemas.

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request.
Ticket will be reopened if pull request rejected.
