### ISSUE TITLE
Datastructure: Attribute "assignmentStatus" and Measure "usageStatus" disappeared

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#66]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/4

A change to add a a simple unique "IsMandatory" boolean property for attributes and measures was agreed by the TWG at the 16 June 'public review mid review meeting'.

**Comment by glennmdt** [comment]
Revised approach approved by the SDMX TWG 27 July 2021 to instead add a new `usage="mandatory|optional"` flag for Data Attributes and Measures, replacing the deprecated assignmentStatus and usageStatus.

Reference: https://github.com/sdmx3mdt/public-consultation/issues/4

**Comment by jgager** [comment]
I assume the default is optional since the isMandatory default was false, correct?

**Comment by glennmdt** [comment]
@jgager asked "I assume the default is optional since the isMandatory default was false, correct?"
Sorry, I missed this question, but it sounds reasonable.

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request.
Ticket will be reopened if pull request rejected.
