### ISSUE TITLE
Remove references to "reports" in descriptions of metadata-related structures

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#68]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/2

I guess 'metadata reports' are now 'metadata sets' or just 'reference metadata' ;-)

**Comment by jgager** [comment]
@glennmdt I believe these have already been addressed at the schema level. If there are specific cases I may have missed, feel free to re-open.

**Comment by glennmdt** [comment]
Pushed to feature branch Commit 13
https://github.com/sdmx3mdt/sdmx-ml/commit/3dcfb8fc3b398e994ccb9f1779d828a7dced01b7
