### ISSUE TITLE
Improve RegEx for SemanticVersionReferenceType

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#71]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/22

Proposed improvement to the Semantic Version regex.

Initial Action - Advise whether it's technically feasible and sensible.

**Comment by jgager** [comment]
In XML schema, you can specify multiple patterns. This accomplishes the goal and is easier to understand in my opinion:

`
		<xs:restriction base="xs:string">
			<xs:pattern value="((0|[1-9]\d*)\+?)(\.((0|[1-9]\d*))){2}"/>
			<xs:pattern value="((0|[1-9]\d*))(\.((0|[1-9]\d*)\+?))(\.((0|[1-9]\d*)))"/>
			<xs:pattern value="((0|[1-9]\d*)\+?)(\.((0|[1-9]\d*)))(\.((0|[1-9]\d*)\+?))"/>
		</xs:restriction>
`
