### ISSUE TITLE
Review RegEx expressions (use ^ to limit the string start and $ to limit the string end)

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#72]
Reference: https://github.com/sdmx3mdt/public-consultation/issues/21

Proposed change to encapsulate regex within '^' and '$' to ensure there are no unwanted characters at the beginning and end of the string.

Initial Action - assess whether this is needed and technically feasible in the XML schemas

**Comment by jgager** [comment]
These are implied in XML Schema regex. Here is a good [write up](https://www.regular-expressions.info/xml.html#:~:text=XML%20schema%20always%20implicitly%20anchors,with%20the%20pattern%20%5Eregexp%24) for reference purposes.

**Comment by glennmdt** [comment]
Noted that no change is required.
Closing ticket.
