### ISSUE TITLE
Revise MSD reference in DSD to allow nested MSD metadata attributes

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#79]
Modifications to support hierarchical Metadata Attributes in MSDs that are linked to DSDs.

J - information from Jens is that you have already recommended not altering the metadata message, instead modifying the data message to harmonise the Metadata Attribute reporting approach across both data and metadata. 

In essence, the proposal is to allow a metadataset to be embedded in the data message.

Details in the attached document:
[SDMX TWG TF2 - public review issues #14 - MetadataStructure Reference in DSD must allow using nested MSD metadata attributes.docx](https://github.com/glennmdt/sdmx-ml/files/6894544/SDMX.TWG.TF2.-.public.review.issues.14.-.MetadataStructure.Reference.in.DSD.must.allow.using.nested.MSD.metadata.attributes.docx)

Reference to the Public Consultation ticket:
https://github.com/sdmx3mdt/public-consultation/issues/14

**Comment by jgager** [comment]
@glennmdt 

1. should there be a restriction to one Metadata tag per container (e.g. DataSet, Group, Series, Obs).
2. the data set allows for a mix of Atts, Group, Series, Obs (no specific order and all can be repeated multiple times). Should Metadata be included in this repeated choice, or should it be placed after these elements? 
3. group, series, and obs have ordered elements; should this be updated for any order or left as is? If left as is, where should Metadata occur in the order?

**Comment by glennmdt** [comment]
@jgager I can't really answer these questions, and Jens Dosse is now on leave until the very end of August.
Maybe Matt @agent96 can advise. 

As far as I understand though, it should be possible to place Metadata at any point in the message where simple Metadata Attributes can currently go.

**Comment by glennmdt** [comment]
Added to sdmx-twg develop branch pull request. 
Ticket will be reopened if pull request rejected.
