### ISSUE TITLE
DSD - enforce the rule that the TimeDimension is the last in the list of dimensions

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#88]
Relating to public consultation issue https://github.com/sdmx3mdt/public-consultation/issues/50

Decision from the 02 Sept 2021 release candidate approval meeting:
Enforce the rule that the TimeDimension is the last in the list of dimensions in the DSD.

It implies that the TimeDimension's 'position' attribute is redundant and should be removed.

**Comment by jgager** [comment]
The dimension list was a choice of dimension/time dimension with a cardinality of 1..n (uniqueness constraint ensured only on time dimension could be declared). This will now be a sequence. I assume time dimension is optional. Is Dimension optional as well (i.e. could one have a DSD with the only dimension being time)?

**Comment by glennmdt** [comment]
@jgager it should be a sequence of:
1..n dimensions
0..1 time dimensions

Yes, time dimension is optional because of the need to support unit record data without any concept of time.

However, there should be a minimum of 1 natural dimensions I think because the REST API amongst other bits of the standard assume that. There is a change request to allow DSDs with 0 dimensions, but that has been deferred until after the 3.0 release because the impact is too great at this late stage of the release cycle.

**Comment by glennmdt** [comment]
Closed - included in sdmx3mdt repo commit 14
