### ISSUE TITLE
Structure Maps - Component Map should be optional

### ISSUE THREAD

**Issue by agent96** [glennmdt/sdmx-ml#94]
Currently at least 1 Component Map is required by the schema, but this means it is not possible to output the structure as a stub

**Comment by jgager** [comment]
@agent96 Source and Target are also required. Are those part of the stub or should they be optional as well?

**Comment by agent96** [comment]
Good question.  I don't know what is best here.  For a pure stub I would say they should be optional, but if a stub contains the source and target it would not be a disaster.  If it's not been done now I would say leave it alone.

**Comment by glennmdt** [comment]
Closed - included in sdmx3mdt repo commit 14
